# Generated by Django 5.2.7 on 2025-11-03 20:16

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la página')),
                ('client_name', models.CharField(max_length=200, verbose_name='Cliente / marca')),
                ('service_type', models.CharField(help_text='Ej: Landing, Web completa, E-commerce, Branding', max_length=100, verbose_name='Tipo de servicio')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Contenido / objetivos')),
                ('reference_image', models.ImageField(upload_to='briefs/', verbose_name='Imagen de referencia')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefs', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
